# frozen_string_literal: true

module InputObjects
  class CsrfToken < BaseInputObject
    description 'A Csrf Token generated by the server with an identifier generated by the client'

    argument :client_token_id,
             String,
             required: true,
             description: 'The identifier for the token generated client-side'

    argument :token,
             String,
             required: true,
             description: 'The token that was generated from the server to validate'
  end
end
